# cfn/compute.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Compute stack (EC2 in private app subnets, registered to ALB Target Group, no SSH; uses SSM role)

Parameters:
  PrivateAppSubnet1Id:
    Type: AWS::EC2::Subnet::Id
  PrivateAppSubnet2Id:
    Type: AWS::EC2::Subnet::Id
  AppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  InstanceProfileName:
    Type: String
    Description: Instance profile name from security.yaml outputs
  TargetGroupArn:
    Type: String
    Description: Target group ARN from alb.yaml outputs

  AppPort:
    Type: Number
    Default: 5000

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Linux 2023 (or AL2) AMI ID

  InstanceType:
    Type: String
    Default: t3.micro

  DesiredCapacity:
    Type: Number
    Default: 1
  MinSize:
    Type: Number
    Default: 1
  MaxSize:
    Type: Number
    Default: 2

  # App settings (env vars)
  FlaskSecret:
    Type: String
    NoEcho: true
    Default: change-me
  DbHost:
    Type: String
    Description: RDS endpoint address (from database.yaml output)
  DbName:
    Type: String
    Default: StudentProjectDB
  DbUser:
    Type: String
    NoEcho: true
  DbPass:
    Type: String
    NoEcho: true
  DbPort:
    Type: Number
    Default: 3306

  # Optional: used by MySQL proc encryption for phone AES_ENCRYPT (your migration SQL)
  PhoneEncKey:
    Type: String
    NoEcho: true
    Default: change-me-phone-key

Resources:
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub student-portal-lt-${AWS::StackName}
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref InstanceProfileName
        SecurityGroupIds:
          - !Ref AppSecurityGroupId
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e

            # --- Basic hardening / updates ---
            yum update -y

            # --- Install Python & tools ---
            yum install -y python3 git
            python3 -m pip install --upgrade pip

            # --- App folder ---
            mkdir -p /opt/student-portal
            cd /opt/student-portal

            # ==============================
            # OPTION A (recommended for demo):
            # You bake the app into AMI OR
            # you SSM into instance and git clone manually.
            #
            # OPTION B (automatic git clone):
            # set a public repo + uncomment below
            # ==============================
            # git clone https://github.com/YOUR_ORG/YOUR_REPO.git .
            #
            # Then install requirements if you provide requirements.txt
            # python3 -m pip install -r requirements.txt

            # --- Export env vars (matches app.py) ---
            cat > /etc/profile.d/student_portal_env.sh <<'EOF'
            export FLASK_SECRET='${FlaskSecret}'
            export DB_HOST='${DbHost}'
            export DB_NAME='${DbName}'
            export DB_USER='${DbUser}'
            export DB_PASS='${DbPass}'
            export DB_PORT='${DbPort}'
            export PHONE_ENC_KEY='${PhoneEncKey}'
            export PORT='${AppPort}'
            export COOKIE_SECURE='true'
            EOF
            chmod 600 /etc/profile.d/student_portal_env.sh

            # --- Create systemd service to run gunicorn ---
            # NOTE: requires your app code + gunicorn installed.
            python3 -m pip install flask flask-wtf pymysql gunicorn

            cat > /etc/systemd/system/student-portal.service <<EOF
            [Unit]
            Description=Student Project Portal (Flask)
            After=network.target

            [Service]
            Type=simple
            WorkingDirectory=/opt/student-portal
            Environment=FLASK_SECRET=${FlaskSecret}
            Environment=DB_HOST=${DbHost}
            Environment=DB_NAME=${DbName}
            Environment=DB_USER=${DbUser}
            Environment=DB_PASS=${DbPass}
            Environment=DB_PORT=${DbPort}
            Environment=PHONE_ENC_KEY=${PhoneEncKey}
            Environment=PORT=${AppPort}
            Environment=COOKIE_SECURE=true
            ExecStart=/usr/local/bin/gunicorn -w 2 -b 0.0.0.0:${AppPort} app:app
            Restart=always
            RestartSec=3

            [Install]
            WantedBy=multi-user.target
            EOF

            systemctl daemon-reload
            systemctl enable student-portal.service

            # If app.py isn't there yet, service will fail — that's fine for assignment.
            # Once you push code or git clone, restart:
            # systemctl restart student-portal.service
            systemctl start student-portal.service || true

  AppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateAppSubnet1Id
        - !Ref PrivateAppSubnet2Id
      DesiredCapacity: !Ref DesiredCapacity
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 120
      Tags:
        - Key: Name
          Value: student-portal-app
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Value: !Ref AppAutoScalingGroup
  LaunchTemplateId:
    Value: !Ref AppLaunchTemplate
