# cfn/database.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Database stack (RDS MySQL in private subnets, encrypted, not public)

Parameters:
  PrivateDbSubnet1Id:
    Type: AWS::EC2::Subnet::Id
  PrivateDbSubnet2Id:
    Type: AWS::EC2::Subnet::Id
  DbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  DbName:
    Type: String
    Default: StudentProjectDB
  DbUsername:
    Type: String
    NoEcho: true
  DbPassword:
    Type: String
    NoEcho: true
  DbInstanceClass:
    Type: String
    Default: db.t3.micro
  AllocatedStorage:
    Type: Number
    Default: 20
  MultiAZ:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

Conditions:
  UseMultiAZ: !Equals [!Ref MultiAZ, "true"]

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: student-portal-db-subnets
      SubnetIds:
        - !Ref PrivateDbSubnet1Id
        - !Ref PrivateDbSubnet2Id

  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageEncrypted: true
      PubliclyAccessible: false
      MultiAZ: !If [UseMultiAZ, true, false]
      BackupRetentionPeriod: 7
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroupId
      DBName: !Ref DbName
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      DeletionProtection: false

Outputs:
  DbEndpoint:
    Value: !GetAtt RdsInstance.Endpoint.Address
  DbPort:
    Value: !GetAtt RdsInstance.Endpoint.Port
  DbNameOut:
    Value: !Ref DbName
