# cfn/root.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Root nested stack (Network -> Security -> Database -> ALB -> Compute)

Parameters:
  # Nested stacks require TemplateURL accessible over HTTPS (usually S3).
  # For assignment: keep placeholder and explain "upload cfn/ templates to S3 first".
  BaseTemplateUrl:
    Type: String
    Default: https://YOUR-S3-BUCKET.s3.amazonaws.com/cfn
    Description: Base URL where cfn templates are uploaded (e.g., https://bucket.s3.amazonaws.com/cfn)

  AppPort:
    Type: Number
    Default: 5000

  # ALB HTTPS requires ACM certificate ARN (can be placeholder for documentation)
  AcmCertArn:
    Type: String
    Default: arn:aws:acm:REGION:ACCOUNT:certificate/PLACEHOLDER
    Description: ACM cert ARN for HTTPS listener

  # Compute requires an AMI ID (set real value when deploying)
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Linux AMI ID (set when deploying)

  InstanceType:
    Type: String
    Default: t3.micro

  DesiredCapacity:
    Type: Number
    Default: 1
  MinSize:
    Type: Number
    Default: 1
  MaxSize:
    Type: Number
    Default: 2

  # App secrets / DB credentials
  FlaskSecret:
    Type: String
    NoEcho: true
    Default: change-me

  PhoneEncKey:
    Type: String
    NoEcho: true
    Default: change-me-phone-key

  DbName:
    Type: String
    Default: StudentProjectDB
  DbUsername:
    Type: String
    NoEcho: true
  DbPassword:
    Type: String
    NoEcho: true
  DbInstanceClass:
    Type: String
    Default: db.t3.micro
  AllocatedStorage:
    Type: Number
    Default: 20
  MultiAZ:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateUrl}/network.yaml"
      Parameters: {}

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateUrl}/security.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        AppPort: !Ref AppPort

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateUrl}/database.yaml"
      Parameters:
        PrivateDbSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateDbSubnet1Id
        PrivateDbSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateDbSubnet2Id
        DbSecurityGroupId: !GetAtt SecurityStack.Outputs.DbSecurityGroupId
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        DbInstanceClass: !Ref DbInstanceClass
        AllocatedStorage: !Ref AllocatedStorage
        MultiAZ: !Ref MultiAZ

  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateUrl}/alb.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        AlbSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbSecurityGroupId
        AppPort: !Ref AppPort
        AcmCertArn: !Ref AcmCertArn

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - DatabaseStack
      - SecurityStack
      - NetworkStack
    Properties:
      TemplateURL: !Sub "${BaseTemplateUrl}/compute.yaml"
      Parameters:
        PrivateAppSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateAppSubnet1Id
        PrivateAppSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateAppSubnet2Id
        AppSecurityGroupId: !GetAtt SecurityStack.Outputs.AppSecurityGroupId
        InstanceProfileName: !GetAtt SecurityStack.Outputs.InstanceProfileName
        TargetGroupArn: !GetAtt AlbStack.Outputs.TargetGroupArn

        AppPort: !Ref AppPort
        AmiId: !Ref AmiId
        InstanceType: !Ref InstanceType

        DesiredCapacity: !Ref DesiredCapacity
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize

        FlaskSecret: !Ref FlaskSecret
        DbHost: !GetAtt DatabaseStack.Outputs.DbEndpoint
        DbName: !Ref DbName
        DbUser: !Ref DbUsername
        DbPass: !Ref DbPassword
        DbPort: 3306
        PhoneEncKey: !Ref PhoneEncKey

Outputs:
  VpcId:
    Value: !GetAtt NetworkStack.Outputs.VpcId

  AlbDnsName:
    Value: !GetAtt AlbStack.Outputs.AlbDnsName

  DbEndpoint:
    Value: !GetAtt DatabaseStack.Outputs.DbEndpoint

  AutoScalingGroupName:
    Value: !GetAtt ComputeStack.Outputs.AutoScalingGroupName
